// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnaajzmbkisybwnjeiie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuYWFqem1ia2lzeWJ3bmplaWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NjY0NTIsImV4cCI6MjA5MDA0MjQ1Mn0.4YL8sotyk8noKqUMMcciWSwcIRG4_oy-J4a-B1KJA2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});